Workaround integer conversion issue.
I was seeing the following error:

site-packages\keras\src\backend\tensorflow\numpy.py", line 2079, in signbit
    tf.constant(0x80000000, dtype=tf.int32),
OverflowError: Python int too large to convert to C long

This sign check is present and unchanged in the latest keras src.
May be causing issues on windows pythong because native "int" is 32 bits
even for 64 bit windows installs.

https://github.com/keras-team/keras/blob/master/keras/src/backend/tensorflow/numpy.py#L2066

Digging into it, it looks like very small positive floats were getting sorted wrong in
https://github.com/jax-ml/jax/issues/24280, which may be the origin of
this special sign check. For my purposes, the type is float32 and the
naive signcheck "return x < 0" avoids the overflow error, though at the
risk of bringing back issue 24280 or something like it (?)